---

- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Assure gitea is installed
    kubernetes.core.helm:
      name: gitea
      chart_repo_url: "https://charts.bitnami.com/bitnami"
      chart_ref: gitea
      release_namespace: default
      release_state: present
    register: result
  - name: Assure gitea is installed
    ansible.builtin.assert:
      that: 
      - result.status.status == "deployed"
